export const en = [
  {
    id: "1",
    title: "Aksazlar Plajı",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "2",
    title: "Belcekız Plajı",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "3",
    title: "Çalış Plajı",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "4",
    title: "Gemile Koyu ",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "5",
    title: "Göcek Tersane Adası",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "6",
    title: "Günlüklü Koyu",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "7",
    title: "Help Beach & Yacht Club",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "8",
    title: "İnlice Halk Plajı",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "9",
    title: "Kabak Koyu ",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "10",
    title: "Kaputaş Plajı",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "11",
    title: "Karaot Plajı",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "12",
    title: "Katrancı Koyu",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "13",
    title: "Keçiler Koyu",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "14",
    title: "Kelebekler Vadisi",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "15",
    title: "Kıdrak Koyu",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "16",
    title: "Kleopatra Hamamı Koyu",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "17",
    title: "Kuleli Koyu",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "18",
    title: "Kumburnu Halk Plajı",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "19",
    title: "Ölüdeniz",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "20",
    title: "Patara Plajı",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "21",
    title: "Sarıgerme Plajı",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "22",
    title: "Soğuksu Koyu",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "23",
    title: "Şövalye Adası",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "24",
    title: "Turunç Pınarı Koyu",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  {
    id: "25",
    title: "Uzunyurt Koyu",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
];
