export const en = [
  {
    id: "1",
    title: "Aksazlar Plajı",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "logo.png",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
    pageCoverId: "cover",
    pageCoverTemplate: "thirds",
    pageCoverImageAlt: "Fethiye Aksazlar Plajı",
    pageCoverImageUrl: "fethiye-aksazlar-koyu-cover.jpg",
    pageCoverImageWidth: "720",
    pageCoverImageHeight: "1024",
    pageCoverImageLayout: "fixed",
    // pageOneId: "1",
    // pageOneImageAlt: "Fethiye Aksazlar Plajı",
    // pageOneImageUrl: "aksazlar-koyu.jpg",
    // pageOneImageWidth: "720",
    // pageOneImageHeight: "1024",
    // pageOneImageLayout: "fixed",
  },
  {
    id: "2",
    title: "Çalış Plajı",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Çalış Plajı",
    publisherlogoSrc: "logo.png",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
    pageCoverId: "cover",
    pageCoverTemplate: "thirds",
    pageCoverImageAlt: "Fethiye Çalış Plajı",
    pageCoverImageUrl: "fethiye-calis-plaji-cover.jpg",
    pageCoverImageWidth: "720",
    pageCoverImageHeight: "1024",
    pageCoverImageLayout: "fixed",
    // pageOneId: "1",
    // pageOneImageAlt: "Fethiye Aksazlar Plajı",
    // pageOneImageUrl: "aksazlar-koyu.jpg",
    // pageOneImageWidth: "720",
    // pageOneImageHeight: "1024",
    // pageOneImageLayout: "fixed",
  },
  {
    id: "3",
    title: "Belcekız Plajı",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Belcekız Plajı",
    publisherlogoSrc: "logo.png",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
    pageCoverId: "cover",
    pageCoverTemplate: "thirds",
    pageCoverImageAlt: "Fethiye Belcekız Plajı",
    pageCoverImageUrl: "fethiye-belcekız-plajı-cover.jpg",
    pageCoverImageWidth: "720",
    pageCoverImageHeight: "1024",
    pageCoverImageLayout: "fixed",
    // pageOneId: "1",
    // pageOneImageAlt: "Fethiye Aksazlar Plajı",
    // pageOneImageUrl: "aksazlar-koyu.jpg",
    // pageOneImageWidth: "720",
    // pageOneImageHeight: "1024",
    // pageOneImageLayout: "fixed",
  },
  {
    id: "4",
    title: "Gemile Koyu",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Gemile Koyu",
    publisherlogoSrc: "logo.png",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
    pageCoverId: "cover",
    pageCoverTemplate: "thirds",
    pageCoverImageAlt: "Fethiye Gemile Koyu",
    pageCoverImageUrl: "fethiye-gemile-koyu-cover.jpg",
    pageCoverImageWidth: "720",
    pageCoverImageHeight: "1024",
    pageCoverImageLayout: "fixed",
    // pageOneId: "1",
    // pageOneImageAlt: "Fethiye Aksazlar Plajı",
    // pageOneImageUrl: "aksazlar-koyu.jpg",
    // pageOneImageWidth: "720",
    // pageOneImageHeight: "1024",
    // pageOneImageLayout: "fixed",
  },
  {
    id: "5",
    title: "Göcek Tersane Adası",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Göcek Tersane Adası",
    publisherlogoSrc: "logo.png",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
    pageCoverId: "cover",
    pageCoverTemplate: "thirds",
    pageCoverImageAlt: "Fethiye Göcek Tersane Adası",
    pageCoverImageUrl: "fethiye-göcek-tershane-adası-cover.jpg",
    pageCoverImageWidth: "720",
    pageCoverImageHeight: "1024",
    pageCoverImageLayout: "fixed",
    // pageOneId: "1",
    // pageOneImageAlt: "Fethiye Aksazlar Plajı",
    // pageOneImageUrl: "aksazlar-koyu.jpg",
    // pageOneImageWidth: "720",
    // pageOneImageHeight: "1024",
    // pageOneImageLayout: "fixed",
  },
  {
    id: "7",
    title: "İnlice Halk Plajı",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye İnlice Halk Plajı",
    publisherlogoSrc: "logo.png",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
    pageCoverId: "cover",
    pageCoverTemplate: "thirds",
    pageCoverImageAlt: "Fethiye İnlice Halk Plajı",
    pageCoverImageUrl: "fethiye-inlice-halk-plajı-cover.jpg",
    pageCoverImageWidth: "720",
    pageCoverImageHeight: "1024",
    pageCoverImageLayout: "fixed",
    // pageOneId: "1",
    // pageOneImageAlt: "Fethiye Aksazlar Plajı",
    // pageOneImageUrl: "aksazlar-koyu.jpg",
    // pageOneImageWidth: "720",
    // pageOneImageHeight: "1024",
    // pageOneImageLayout: "fixed",
  },
  {
    id: "6",
    title: "Günlüklü Koyu",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Günlüklü Koyu",
    publisherlogoSrc: "logo.png",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
    pageCoverId: "cover",
    pageCoverTemplate: "thirds",
    pageCoverImageAlt: "Fethiye Günlüklü Koyu",
    pageCoverImageUrl: "fethiye-günlüklü-koyu-cover.jpg",
    pageCoverImageWidth: "720",
    pageCoverImageHeight: "1024",
    pageCoverImageLayout: "fixed",
    // pageOneId: "1",
    // pageOneImageAlt: "Fethiye Aksazlar Plajı",
    // pageOneImageUrl: "aksazlar-koyu.jpg",
    // pageOneImageWidth: "720",
    // pageOneImageHeight: "1024",
    // pageOneImageLayout: "fixed",
  },
];
