export const en = [
  {
    id: "1",
    title: "Aksazlar Plajı",
    publisher: "Bülent ALA",
    storyTitle: "Fethiye Aksazlar Plajı",
    publisherlogoSrc: "aksazlar-koyu.jpg",
    posterPortraitSrc: "aksazlar-koyu.jpg",
    posterSquareSrc: "aksazlar-koyu.jpg",
    posterLandscapeSrc: "aksazlar-koyu.jpg",
  },
  { id: "2", title: "Belcekız Plajı" },
  { id: "3", title: "Çalış Plajı" },
  { id: "4", title: "Gemile Koyu " },
  { id: "5", title: "Göcek Tersane Adası" },
  { id: "6", title: "Günlüklü Koyu" },
  { id: "7", title: "Help Beach & Yacht Club" },
  { id: "8", title: "İnlice Halk Plajı" },
  { id: "9", title: "Kabak Koyu " },
  { id: "10", title: "Kaputaş Plajı" },
  { id: "11", title: "Karaot Plajı" },
  { id: "12", title: "Katrancı Koyu" },
  { id: "13", title: "Keçiler Koyu" },
  { id: "14", title: "Kelebekler Vadisi" },
  { id: "15", title: "Kıdrak Koyu" },
  { id: "16", title: "Kleopatra Hamamı Koyu" },
  { id: "17", title: "Kuleli Koyu" },
  { id: "18", title: "Kumburnu Halk Plajı" },
  { id: "19", title: "Ölüdeniz" },
  { id: "20", title: "Patara Plajı" },
  { id: "21", title: "Sarıgerme Plajı" },
  { id: "22", title: "Soğuksu Koyu" },
  { id: "23", title: "Şövalye Adası" },
  { id: "24", title: "Turunç Pınarı Koyu" },
  { id: "25", title: "Uzunyurt Koyu" },
];
